name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev cmake build-essential
    
    - name: Set up compiler
      run: |
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt-get install -y clang
          echo "CC=clang" >> $GITHUB_ENV
        else
          echo "CC=gcc" >> $GITHUB_ENV
        fi
    
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build
      run: |
        cmake --build build --config ${{ matrix.build_type }}
    
    - name: Test executable
      run: |
        file build/xskat
        ldd build/xskat
    
    - name: Upload artifact
      if: matrix.compiler == 'gcc' && matrix.build_type == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: xskat-linux
        path: build/xskat

  package:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev cmake build-essential
    
    - name: Configure and build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
    
    - name: Create package
      run: |
        cd build
        cpack
    
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: xskat-package
        path: build/xskat-*.tar.gz